services:
  db:
    image: postgres:17
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s
  drf_booking:
    build: .
    container_name: booking_api
    restart: always
    entrypoint: ["/app/entrypoint.sh"]
    command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  pg_data:
